version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql_database
    environment:
      MYSQL_ROOT_PASSWORD: placeholder
      MYSQL_DATABASE: map
      MYSQL_HOST: localhost
    volumes:
      - db_data:/var/lib/mysql
      - ./init_db:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
  web:
    build: .
    ports:
      - "8080:8080"
    develop:
      watch:
        - action: sync
          path: .
          target: /code
    depends_on:
      - db

volumes:
  db_data: