version: '3.8'

services:
  db:
        image: mysql:8.0
        ports:
          - "3306:3306"
        environment:
          - MYSQL_ROOT_HOSTS=%
          - MYSQL_DATABASE=map
          - MYSQL_ROOT_PASSWORD=pasword123
        volumes:
          - ./docker/volume_mysql:/var/lib/mysql
          # why is this not working?
          - ./init_db:/docker-entrypoint-initdb.d
#   web:
#     build: .
#     ports:
#       - "8080:8080"
#     develop:
#       watch:
#         - action: sync
#           path: .
#           target: /code
#     depends_on:
#       - db

# volumes:
#   db_data: