services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      # - MYSQL_HOST=db
      # - MYSQL_USER=${DB_USER}
      # - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      # - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_HOST=db
      - MYSQL_USER=${DB_HOST}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      # - MYSQL_DATABASE=${DB_NAME}
      # - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      # - MYSQL_USER=${DB_USER}
      # - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_HOST=db
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./docker/volume_mysql:/var/lib/mysql
      - ./init_db:/docker-entrypoint-initdb.d

volumes:
  db_data: