version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: test_docker_compose
    environment:
      MYSQL_ROOT_PASSWORD: pasword123
      MYSQL_DATABASE: test_docker_compose
      MYSQL_HOST: localhost
    volumes:
      - db_data:/var/lib/mysql
      - ./init_db:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

volumes:
  db_data: