services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:latest
    ports:
      - "3306:3306"
    environment:
      - POSTGRES_PASSWORD=${password}
      - POSTGRES_DB=${database}
      - POSTGRES_USER=${user}
      
    volumes:
      - ./docker/volume_mysql:/var/lib/mysql
      - ./init_db:/docker-entrypoint-initdb.d

volumes:
  db_data: